# Generated by Django 5.1 on 2024-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('send_from', models.TextField()),
                ('send_to', models.TextField()),
                ('receive_address', models.TextField()),
                ('receive_data', models.DateTimeField()),
                ('deliver_address', models.TextField()),
                ('about_product', models.TextField()),
                ('product_id', models.CharField(max_length=100)),
                ('marking', models.CharField(max_length=100)),
                ('origin_country', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('deliver_path', models.CharField(choices=[('морской', 'Морской'), ('воздушный', 'Воздушный'), ('наземный', 'Наземный'), ('экспресс', 'Экспресс'), ('группирование', 'Группирование'), ('насыпной груз', 'Насыпной груз')], default='морской', max_length=100)),
                ('instruction_paperwork', models.TextField()),
                ('product_insurance', models.TextField()),
                ('other_instructions', models.TextField()),
                ('temp_save', models.TextField()),
                ('special_notes', models.TextField()),
            ],
        ),
    ]
